const http=require("http"),fs=require("fs"),path=require("path"),crypto=require("crypto"),url=require("url");
const ROOT=__dirname,PORT=process.env.PORT||3000,sessions=new Map();
try{for(const l of fs.readFileSync(path.join(ROOT,".env"),"utf8").split(/\r?\n/)){const m=l.match(/^([^#=]+)=(.*)$/);if(m)process.env[m[1].trim()]=m[2].trim()}}catch{}
const load=n=>{try{return JSON.parse(fs.readFileSync(path.join(ROOT,"db",n),"utf8"))}catch{return[]}},save=(n,d)=>fs.writeFileSync(path.join(ROOT,"db",n),JSON.stringify(d,null,2));
const send=(r,s,d,t="application/json")=>{r.writeHead(s,{"Content-Type":t});r.end(t==="application/json"?JSON.stringify(d):d)};
const body=req=>new Promise((ok,fail)=>{let s="";req.on("data",c=>s+=c);req.on("end",()=>{try{ok(s?JSON.parse(s):{})}catch(e){fail(e)}})});
const aut=req=>{let m=(req.headers.cookie||"").match(/tm_session=([^;]+)/);return m&&sessions.has(m[1])};
const ysecret=s=>{try{return Buffer.from(s,"base64").toString("utf8").split(".")[0]}catch{return s}};
async function api(req,res,p){
if(req.method==="GET"&&p==="/api/products")return send(res,200,load("products.json").filter(x=>x.active!==false));
if(req.method==="POST"&&p==="/api/admin/login"){let b=await body(req);if(b.password!==process.env.ADMIN_PASSWORD)return send(res,401,{error:"Clave incorrecta"});let t=crypto.randomBytes(24).toString("hex");sessions.set(t,Date.now()+86400000);res.setHeader("Set-Cookie",`tm_session=${t}; HttpOnly; SameSite=Lax; Path=/`);return send(res,200,{ok:true})}
if(req.method==="POST"&&p==="/api/admin/logout"){let m=(req.headers.cookie||"").match(/tm_session=([^;]+)/);if(m)sessions.delete(m[1]);return send(res,200,{ok:true})}
if(p.startsWith("/api/admin/")&&!aut(req))return send(res,401,{error:"No autorizado"});
if(req.method==="GET"&&p==="/api/admin/products")return send(res,200,load("products.json"));
if(req.method==="POST"&&p==="/api/admin/products"){let b=await body(req),a=load("products.json"),x={id:"p"+crypto.randomBytes(6).toString("hex"),name:b.name,category:b.category||"Otros",price:+b.price,oldPrice:+(b.oldPrice||0),icon:b.icon||"📦",stock:+(b.stock||0),active:true};if(!x.name||x.price<=0)return send(res,400,{error:"Nombre y precio son obligatorios"});a.push(x);save("products.json",a);return send(res,201,x)}
if(req.method==="DELETE"&&p.startsWith("/api/admin/products/")){let id=p.split("/").pop();save("products.json",load("products.json").filter(x=>x.id!==id));return send(res,200,{ok:true})}
if(req.method==="GET"&&p==="/api/admin/orders")return send(res,200,load("orders.json").sort((a,b)=>b.createdAt-a.createdAt));
if(req.method==="POST"&&p==="/api/orders"){let b=await body(req),ps=load("products.json"),items=[];for(const i of b.items||[]){let x=ps.find(q=>q.id===i.id&&q.active!==false);if(!x||i.qty<1||i.qty>x.stock)return send(res,400,{error:"Producto o inventario inválido"});items.push({id:x.id,name:x.name,qty:i.qty,price:x.price})}if(!items.length)return send(res,400,{error:"Carrito vacío"});let total=items.reduce((s,x)=>s+x.price*x.qty,0),o={id:Date.now().toString(36).slice(-12),createdAt:Date.now(),status:"pending",paymentStatus:"pending",customer:b.customer||{},items,total};let a=load("orders.json");a.push(o);save("orders.json",a);return send(res,201,o)}
if(req.method==="POST"&&p==="/api/yappy/order"){let b=await body(req);if(!process.env.YAPPY_MERCHANT_ID||!process.env.YAPPY_SECRET_KEY)return send(res,503,{error:"Yappy no configurado"});let o=load("orders.json").find(x=>x.id===b.orderId);if(!o)return send(res,404,{error:"Pedido no encontrado"});try{let base=process.env.YAPPY_ENV==="prod"?"https://apipagosbg.bgeneral.cloud":"https://api-comecom-uat.yappycloud.com";let vr=await fetch(base+"/payments/validate/merchant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({merchantId:process.env.YAPPY_MERCHANT_ID,urlDomain:process.env.YAPPY_DOMAIN})});let v=await vr.json(),token=v?.body?.token;if(!token)return send(res,502,{error:"Yappy no autorizó el comercio",detail:v});let payload={merchantId:process.env.YAPPY_MERCHANT_ID,orderId:o.id,domain:process.env.YAPPY_DOMAIN,paymentDate:Date.now(),aliasYappy:process.env.YAPPY_ALIAS||"",ipnUrl:process.env.YAPPY_IPN_URL,discount:"0.00",taxes:"0.00",subtotal:o.total.toFixed(2),total:o.total.toFixed(2)};let rr=await fetch(base+"/payments/payment-wc",{method:"POST",headers:{"Content-Type":"application/json","Authorization":token},body:JSON.stringify(payload)});return send(res,rr.ok?200:502,await rr.json())}catch(e){return send(res,502,{error:"No se pudo conectar con Yappy"})}}
if(req.method==="GET"&&p==="/api/yappy/ipn"){let q=url.parse(req.url,true).query,{orderId,status,hash,domain}=q;if(!orderId||!status||!hash||!domain)return send(res,400,{success:false});let sig=crypto.createHmac("sha256",ysecret(process.env.YAPPY_SECRET_KEY||"")).update(orderId+status+domain).digest("hex");if(hash!==sig)return send(res,401,{success:false});let a=load("orders.json"),i=a.findIndex(x=>x.id===orderId);if(i<0)return send(res,404,{success:false});a[i].paymentStatus=status==="E"?"paid":"failed";a[i].status=status==="E"?"paid":a[i].status;save("orders.json",a);return send(res,200,{success:true})}
return false}
const mime={".html":"text/html;charset=utf-8",".js":"text/javascript;charset=utf-8",".css":"text/css;charset=utf-8",".png":"image/png"};
http.createServer(async(req,res)=>{let p=url.parse(req.url).pathname;if(p.startsWith("/api/")){let x=await api(req,res,p);if(x!==false)return}let f=p==="/"?"/index.html":p;if(p==="/admin")f="/admin.html";let fp=path.join(ROOT,"public",f);fs.readFile(fp,(e,d)=>e?send(res,404,"Not found","text/plain"):send(res,200,d,mime[path.extname(fp)]||"text/plain"))}).listen(PORT,()=>console.log("Todomix: http://localhost:"+PORT));